#list of users

SCREEN_NAME = [
                "russliquid",
                "Devon_Davis_23",
                "morg_michele",
                "stevejspencer",
##                "minimightymaz",
                "_radiantradish_","karahwilson15",
                "TFS_Punisher",
                "StuartKenny33","TheCouchman",
                "ErinnUndefined",
                "terraphim",
                "manxiouslife",
                "imnormgoh",
                "Mrs_MTaurus",
                "megcampbelluk",
##                "DANAnotMISSANN",
                "hiwassee_river",
##                "TylerBarnett95",
##location not good                "awinsarahm",
                "Sumidian_",
                "peculiarswift","felixunger1999",
                "heyitsnadiya","aliha_nirvana",
                "shxniacarter",
                "Shantaln22",
                "ngwu_chioma",
                "JulieDiCaro",
                "OneMugManTwo",
##                "BlancDevan",
                "Shaunski15",
                "YvonneCovey",
                "EmmettJana",
                "kuuipoleeanne",
                "carol08156",
                "weenerhotsauce",
                "miroreos",
                "caIdodecana",
                "ophxliac",
                "lilvsvp",
                "fedupperson78"
            ]
